#!/bin/bash
echo          ------==Script Creado por GerardoHD==------
echo       ---=Limpiando Ubuntu=---
sleep 1s
echo
#!/bin/bash
sudo apt clean
sudo apt autoclean
sudo apt autoremove
df -h
sleep 3s
