#!/bin/bash
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD/Linux
echo Script creado para configurar la sesión Debian en Crostini en ChromeOS
echo Se distribuye con la esperanza de que sea útil, pero sin ninguna garantía
sleep 1s
#
sudo sed -i 's/LANG=en_US.UTF-8/LANG=es_MX.UTF-8/g' /etc/default/locale
sudo sed -i 's/en_US.UTF-8/#en_US.UTF-8/g' /etc/locale.gen
sudo sed -i 's/# es_MX.UTF-8/es_MX.UTF-8/g' /etc/locale.gen
sudo locale-gen
sudo apt install apt-utils xdg-user-dirs debconf -y
sudo apt install android-tools-adb android-tools-fastboot -y
sudo apt install manpages-es manpages-es-extra -y
sudo apt install gnome-software menulibre -y
xdg-user-dirs-update
#
sudo apt install calibre flatpak
#
echo  -=Actualizando el sistema=-
sleep 2s
#Actualizando la biblioteca de paquetes
sudo apt update
# Actualizando el sistema
sudo apt upgrade -y
#
echo  -=Limpiando Ubuntu=-
sleep 1s
echo
#!/bin/bash
sudo apt clean
sudo apt autoclean
sudo apt autoremove
#
screenfetch
