#!/bin/bash
echo Se necesita introducir la carpeta del perfil, identificarlo en chrome://version/#profile_path y modificar el u- debajo:
sudo mount /dev/sda27 /home/chronos/u-e10ecca064310dd96be189cd9b425d8c174c3105/MyFiles/EFI
sudo mount /dev/sda28 /home/chronos/u-e10ecca064310dd96be189cd9b425d8c174c3105/MyFiles/Windows
sudo mount /dev/sda30 /home/chronos/u-e10ecca064310dd96be189cd9b425d8c174c3105/MyFiles/Arch
sudo mount /dev/sda31 /home/chronos/u-e10ecca064310dd96be189cd9b425d8c174c3105/MyFiles/Datos
df -hT
