#!/bin/bash
#Descargar-Scripts
echo          ------==Script Creado por GerardoHD==------
echo       ---=Descargando Scripts=---
sleep 3s
echo
#!/bin/bash
cd /usr/local/bin
sudo rm -rf screenfetch
sudo rm -rf Arch-Clean
sudo rm -rf Arch-Poweroff
sudo rm -rf Arch-Reboot
sudo rm -rf Arch-Repair-var
sudo rm -rf Arch-Setup
sudo rm -rf Arch-Update
sudo rm -rf Secure-Boot
sudo rm -rf Systemd-fsck-Setup
sudo rm -rf Tweaks
sudo rm -rf Blue-Script
sudo rm -rf Descargar-Scripts
sudo rm -rf Materia-GDM-Theme
sudo rm -rf Original-GDM-Theme
sudo rm -rf Red-Script
sudo rm -rf ROOT-A
sudo rm -rf STATE
#sudo rm -rf Ubuntu-Clean
#sudo rm -rf Ubuntu-Repair-var
#sudo rm -rf Ubuntu-Setup
#sudo rm -rf Ubuntu-Update
sudo wget -c https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev -O screenfetch
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Clean
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Poweroff
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Reboot
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Repair-var
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Setup
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Arch-Update
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Secure-Boot
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Systemd-fsck-Setup
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Arch/Tweaks
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Blue-Script
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Descargar-Scripts
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Materia-GDM-Theme
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Original-GDM-Theme
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/ROOT-A
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Red-Script
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/STATE
#sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Ubuntu-Clean
#sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Ubuntu-Repair-var
#sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Ubuntu-Setup
#sudo wget -c https://raw.githubusercontent.com/GerardoHD/Linux/master/Scripts/Ubuntu-Update
sudo chmod +x screenfetch
sudo chmod +x Arch-Clean
sudo chmod +x Arch-Poweroff
sudo chmod +x Arch-Reboot
sudo chmod +x Arch-Repair-var
sudo chmod +x Arch-Setup
sudo chmod +x Arch-Update
sudo chmod +x Secure-Boot
sudo chmod +x Systemd-fsck-Setup
sudo chmod +x Tweaks
sudo chmod +x Blue-Script
sudo chmod +x Descargar-Scripts
sudo chmod +x Materia-GDM-Theme
sudo chmod +x Original-GDM-Theme
sudo chmod +x ROOT-A
sudo chmod +x Red-Script
sudo chmod +x STATE
#sudo chmod +x Ubuntu-Clean
#sudo chmod +x Ubuntu-Repair-var
#sudo chmod +x Ubuntu-Setup
#sudo chmod +x Ubuntu-Update
cd /
sleep 1s
clear
screenfetch
echo Recomiendo editar/revisar alguno de los scripts ubicados en:
echo /usr/local/bin/
ls /usr/local/bin/
echo Ejecuta el Script Elegido
