#!/bin/bash
echo	------==Script Creado por GerardoHD==------
sleep 1s
if [ "$(id -u)" -eq 0 ] ; then
	echo " ADVERTENCIA: makepkg no funciona correctamente en una sesión Root "
	echo " Este script usará sudo cuando sea necesario. Deteniendo. "
	echo " Simplemente ejecute este script desde su usuario. "
	exit
fi
#
echo  -=Actualizando Arch Linux=-
sudo mount -o remount,size=4G,noatime /tmp
yay -Syyu --noconfirm
screenfetch
df -hT
date
#
