#!/bin/bash
echo	------==Script Creado por GerardoHD==------
sleep 1s
if [ "$(id -u)" -eq 0 ] ; then
	echo " ADVERTENCIA: makepkg no funciona correctamente en una sesión Root "
	echo " Este script usará sudo cuando sea necesario. Deteniendo. "
	echo " Simplemente ejecute este script desde su usuario. "
	exit
fi
#
echo  -=Limpiando Arch Linux=-
sleep 1s
sudo pacman -Sc --noconfirm
yay -Sc --noconfirm
screenfetch
df -hT
date
#
