#!/bin/bash
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD/Linux
echo Script creado para gestionar un sistema basado en Arch Linux
echo Se distribuye con la esperanza de que sea útil, pero sin ninguna garantía
sleep 1s
if [ "$(id -u)" -eq 0 ] ; then
	echo " ADVERTENCIA: makepkg no funciona correctamente en una sesión Root "
	echo " Este script usará sudo cuando sea necesario. Deteniendo. "
	echo " Simplemente ejecute este script desde su usuario. "
	exit
fi
#
echo Remontando /tmp con tamaño de 4 GB
sudo mount -o remount,size=4G,noatime /tmp
#
echo  -=Acciones disponibles=-
cmd=(dialog --separate-output --checklist "Elige las acciones a realizar (selecciona con tecla espacio)" 22 76 16)
options=(1 "Reparar el error de db.lck" off
	 2 "Actualizar el sistema" on
         3 "Limpiar caché de paquetes" off
         4 "Actualizar y reiniciar" off
         5 "Actualizar y apagar" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
	1)
	  echo  -=Reparando Pacman db.lck-
	  sudo rm -f /var/lib/pacman/db.lck
	  yay -Syu --noconfirm
	  ;;
	2)
	  echo  -=Actualizando Arch Linux=-
	  yay -Syu --noconfirm
	  ;;
	3)
	  echo  -=Limpiando cache de pacman y AUR=-
	  sleep 1s
	  sudo pacman -Sc --noconfirm
	  yay -Sc --noconfirm
	  ;;
	4)
	  echo  -=Actualizando Arch Linux y reiniciando el sistema=-
	  yay -Syu --noconfirm
	  sudo reboot
	  ;;
	5)
	  echo  -=Actualizando Arch Linux y apagando el sistema=-
	  yay -Syu --noconfirm
	  sudo poweroff
	  ;;
    esac
done
#
