#!/bin/bash
echo          ------==Script Creado por GerardoHD==------
echo       ---=Actualizando y reiniciando Arch Linux--
sleep 1s
if [ "$(id -u)" -eq 0 ] ; then
        echo " ADVERTENCIA: Makepkg no compilará paquetes desde AUR en una sesión Root "
        echo " Este Script usará sudo cuando sea necesario. Deteniendo. "
        echo " Simplemente ejecute este Script desde su usuario. "
        exit
fi
#
sudo mount -o remount,size=4G,noatime /tmp
yay -Syyu --noconfirm
sudo reboot
#
