#!/bin/bash
echo  -=Configurar tipografías en GNOME=-
PS3='Elige la familia tipográfica a usar en GNOME Shell: '
options=("Fira Sans" "IBM Plex" "Noto Sans" "Roboto" "Ubuntu" "Salir")
select opt in "${options[@]}"
do
    case $opt in
	"Fira Sans")
	  echo Configurando Fira Sans como tipografía en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Fira Sans 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Fira Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Mono 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Fira Sans Semibold 11'
	  break
	  ;;
	"IBM Plex")
	  echo Configurando IBM Plex como tipografía en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'IBM Plex Sans Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'IBM Plex Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'IBM Plex Mono 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'IBM Plex Sans Semibold 11'
	  break
	  ;;
	"Noto Sans")
	  echo Configurando Noto Sans como tipografía en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Noto Sans Regular Medium 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Noto Sans Semibold 11'
	  break
	  ;;
	"Roboto")
	  echo Configurando Roboto como tipografía en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Roboto Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Roboto Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Roboto Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Roboto Bold 11'
	  break
	  ;;
	"Ubuntu")
	  echo Configurando Ubuntu como tipografía en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Ubuntu Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Ubuntu Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Ubuntu Mono Regular 14'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Ubuntu Bold 11'
	  break
	  ;;
	"Salir")
	  break
	  ;;
 	*) echo invalid option;;
    esac
done
