#!/bin/bash
	echo ------==Script Creado por GerardoHD==------
	echo ---=Descargando Scripts para Systemd-fsck=---
	echo " Este Script deberá ejecutarse en una sesion root "
sleep 3s
echo
#!/bin/bash
sudo cp /usr/lib/systemd/system/systemd-fsck-root.service /etc/systemd/system/systemd-fsck-root.service
sudo echo StandardOutput=null >> /etc/systemd/system/systemd-fsck-root.service
sudo echo StandardError=journal+console >> /etc/systemd/system/systemd-fsck-root.service
sudo cp /usr/lib/systemd/system/systemd-fsck@.service /etc/systemd/system/systemd-fsck@.service
sudo echo StandardOutput=null >> /etc/systemd/system/systemd-fsck@.service
sudo echo StandardError=journal+console >> /etc/systemd/system/systemd-fsck@.service
sudo mkinitcpio -p linux
Secure-Boot
