#!/bin/bash
echo	------==Script Creado por GerardoHD==------
echo Se aconseja usar este script solo una vez despúes de instalar Arch Linux
echo ya que luego los Hooks de Pacman automáticamente regeneran y firman los
echo archivos .efi para Secure Boot
#
sudo -i
mkdir -p /root/Arch-signed
echo root=LABEL=Arch quiet loglevel=1 vga=current rd.systemd.show_status=auto rd.udev.log_priority=3 > /root/Arch-signed/cmdline.txt
#
cat /boot/intel-ucode.img /boot/initramfs-linux.img >> /root/Arch-signed/Arch-signed/Arch-signed.img
#
objcopy \
    --add-section .osrel="/etc/os-release"                              --change-section-vma .osrel=0x20000    \
    --add-section .cmdline="/root/Arch-signed/cmdline.txt"              --change-section-vma .cmdline=0x30000  \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp"  --change-section-vma .splash=0x40000   \
    --add-section .linux="/boot/vmlinuz-linux"                          --change-section-vma .linux=0x2000000  \
    --add-section .initrd="/root/Arch-signed/Arch-signed.img"           --change-section-vma .initrd=0x3000000 \
    /usr/lib/systemd/boot/efi/linuxx64.efi.stub /boot/EFI/Linux/Arch-signed.efi
#
echo -=Creando entrada NVRAM de Arch.efi=-
efibootmgr --create --disk /dev/sda --part 27 --label "Arch Linux" --loader "\EFI\Linux\Arch-signed.efi" --verbose
#
